/*********************************************************************************************************
* Class Name: {{ api_name }} 
* Author: zb185019  
* Description: 
* Versions: Version#    Made By         	Date            Description
*           1.0         {{ author_name }}   {{ todays_date }}     	Initial Creation
*
*********************************************************************************************************/

/*********************************************************************************************************
* Class Name: {{ api_name }} 
* Author: 
* Date: 
*
* Requirement/Project Name: 
*		  
* Description: 
*		 
*		
*		
* Version History: 
*		0.1 -   Initial creation. 
* Available Methods:
*		{{ api_name }}() 		- Constructor
*		
*
*********************************************************************************************************/
public with sharing class {{ api_name }} {
	public {{ api_name }}() {
		
	}
}